#!/usr/bin/env python
# -*- coding: utf-8 -*-
import __future__
import sys
print("===" * 30)
print("SAMPLE INPUT:")
print("===" * 30)
print(open("./challenge_sample_input", 'r').read())
sys.stdin = open("./challenge_sample_input", 'r')
print("===" * 30)
print("SAMPLE OUTPUT:")
print("===" * 30)
print(open("./challenge_sample_output", 'r').read())
print("===" * 30)
print("START")
print("===" * 30)

#!/bin/python
import sys

q = int(raw_input().strip())
for a0 in xrange(q):
    A,B,C = raw_input().strip().split(' ')
    A,B,C = [int(A),int(B),int(C)]
    if C in range(A+1,B):
        print(A,B,C,"C")
    elif C >= A >= B:
        print(A,B,C,"A")
    elif C >= A <= B:
        print(A,B,C,"B")

